R/adjective.R

According to the Urban Dictionary,
'Somethin totally cool, sensational or excellent.'

Add "crackin'"

---

R/adjective.R
R/adverb.R

Update adverb.R with Trustfully

---

R/verb.R

Added a new verb to close #1

---

R/adjective.R

Added the work "Stonking" as an adjective

Added "Stonking" as Adjective

---

R/adjective.R

Add new adjectives

---

R/adjective.R

Added the word 'metal' to adjectives.

Add 'metal' to adjectives

---

R/adjective.R
R/exclamation.R

Remove the awful word 'fabulous'

---

R/adjective.R

Add callipygian

---

R/adverb.R

Added "bigly".
Trending on twitter, must be a thing ;)

added adverb

---

R/exclamation.R

My very very cool PR made during `rstudio::conf` 2017!  Until next time .... end of line.

add the exclamation "booyeah"!

---

R/adjective.R

Bravo is an exclamation, not an adjective

Remove "bravo"

---

R/adjective.R

Adding the "unbelievable" word to the list.

---

R/adjective.R

A pull request from rstudio::conf!

Add "exciting" to list of adjectives.

---

R/adjective.R

Part of Jenny Bryan's workshop

Add "supah" -- the New England version of super

---

R/adjective.R

I have "radical" code. Thanks Rstudio::conf2017!

Add "radical"

---

R/adjective.R

so good, it puts you into a state of no sensibility

Add "stupefying"

---

R/adjective.R

adding wise to the list of adjectives  🤓👵🏻

word to the wise

---

R/adjective.R

add "rockin"

---

R/adjective.R

A totally tubular addition to the adverb list.

Add "tubular"

---

R/exclamation.R

Added "amazeballs"

---

R/package.R

vertors -> vectors
Carried over to man/praise_parts.Rd

fix typo in praise_parts doc

---

R/verb.R

Fix typo: 'preparin' -> 'preparing'

---

R/adjective.R

Just following the [usethis](https://usethis.r-lib.org/articles/pr-functions.html) tutorial.

New adjective: aaahwesome
